#!/usr/bin/env bash
# 0. Nginx likes port 80

#backup default nginx conf file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

#edit the default nginx conf file to listen on port 80
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

#restart nginx to apply changes
sudo service nginx restart
