#!/usr/bin/env bash

my_pid=$$
sudo chmod 777 /var/run
echo "$my_pid" > /var/run/myscript.pid

while true; do
    trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0' SIGTERM
    trap 'echo "Y U no love me?!"; rm /var/run/myscript.pid; exit 0' SIGINT
    echo "To infinity and beyond"
	sleep 1
done


