#!/usr/bin/env bash

echo $$ > /var/run/myscript.pid

terminate_process()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

interrupt_process()
{
    echo "Y U no love me?!"
}

trap 'terminate_process' SIGTERM SIGQUIT
trap 'interrupt_process' SIGINT

while true; do
    echo "To infinity and beyond"
	sleep 1
done

