#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process.

process_name="4-to_infinity_and_beyond"
pid=$(pgrep -fi "$process_name")
second_line=$(echo "$pid" | awk 'NR==2')
kill "$second_line"
